package apply

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/TakuyaYagam1/wahrwelt/Linux/installer/internal/config"
)

func HostVarsNix(s config.State) (string, error) {
	var out bytes.Buffer
	if err := hostVarsTemplate.Execute(&out, s); err != nil {
		return "", fmt.Errorf("render host-vars.nix: %w", err)
	}
	return out.String(), nil
}

type flakeTemplateData struct {
	config.State
	LockMode    LockMode
	WahrweltURL string
}

func FlakeNix(s config.State, lockMode LockMode) (string, error) {
	var out bytes.Buffer
	if err := flakeTemplate.Execute(&out, flakeTemplateData{
		State:       s,
		LockMode:    lockMode,
		WahrweltURL: config.WahrweltPresetFlakeURL(s.Source.Channel, s.Packages.Preset),
	}); err != nil {
		return "", fmt.Errorf("render flake.nix: %w", err)
	}
	return out.String(), nil
}

func ConfigurationNix() string {
	return `{ pkgs, ... }:

{
  imports = [
    ./user
  ];

  environment.systemPackages = with pkgs; [
    # Add system packages here.
  ];
}
`
}

func UserDefaultNix() string {
	return `# Host-local user NixOS modules. This file is preserved by Wahrwelt.
# Put local-only modules and payloads in this directory, then add explicit
# imports below.
{ ... }:

{
  imports = [
    # ./custom.nix
  ];
}
`
}

func HomeNix() string {
	return `# Host-local Home Manager overrides. This file is preserved by Wahrwelt.
{ pkgs, ... }:

{
  home.packages = with pkgs; [
    # Add user packages here.
  ];
}
`
}

var flakeTemplate = template.Must(template.New("flake.nix").Funcs(template.FuncMap{
	"nixString": nixString,
}).Parse(`{
  # Generated by Wahrwelt installer.
  # lock mode: {{ .LockMode }}
  # preset: {{ .Packages.Preset }}
  description = "Host-local Wahrwelt NixOS wrapper";

  inputs = {
{{ if eq .LockMode "independent" }}
    # Temporary compatibility pin: avoid Hyprland 0.56.1 Glaze packaging failure.
    nixpkgs.url = "github:NixOS/nixpkgs?rev=643809054d65fdd466a63e3155b8c498cb483c04";
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-26.05";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

{{ if ne .Packages.Preset "minimal" }}
    quickshell = {
      url = "github:outfoxxed/quickshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    end4-dotfiles = {
      url = "git+https://github.com/end-4/dots-hyprland?submodules=1";
      flake = false;
    };
    end4-pc = {
      url = "github:pctrade/end4-pC";
      flake = false;
    };

    zen-browser = {
      url = "github:youwen5/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
{{ end }}
    neovim-nightly-overlay = {
      url = "github:nix-community/neovim-nightly-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
    nix-snapd = {
      url = "github:nix-community/nix-snapd";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix = {
      url = "github:danth/stylix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    wahrwelt = {
      url = {{ nixString .WahrweltURL }};
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nixpkgs-stable.follows = "nixpkgs-stable";
      inputs.home-manager.follows = "home-manager";
{{ if ne .Packages.Preset "minimal" }}
      inputs.quickshell.follows = "quickshell";
      inputs.end4-dotfiles.follows = "end4-dotfiles";
      inputs.end4-pc.follows = "end4-pc";
      inputs.zen-browser.follows = "zen-browser";
{{ end }}
      inputs.neovim-nightly-overlay.follows = "neovim-nightly-overlay";
      inputs.nixos-hardware.follows = "nixos-hardware";
      inputs.nix-snapd.follows = "nix-snapd";
      inputs.sops-nix.follows = "sops-nix";
      inputs.nix-index-database.follows = "nix-index-database";
      inputs.stylix.follows = "stylix";
    };
{{ else }}
    wahrwelt.url = {{ nixString .WahrweltURL }};
{{ end }}
{{ if .Features.SecureBoot }}
    lanzaboote = {
      url = "github:nix-community/lanzaboote";
{{ if eq .LockMode "independent" }}
      inputs.nixpkgs.follows = "nixpkgs";
{{ end }}
    };
{{ end }}
  };

  outputs = inputs@{ wahrwelt, ... }:
    let
      system = "x86_64-linux";
      hostname = {{ nixString .Host.Hostname }};
    in
    {
      nixosConfigurations.${hostname} = wahrwelt.lib.mkWahrweltHost {
        inherit system hostname;

        hostVars = ./host-vars.nix;
        hardware = ./hardware-configuration.nix;
        hashedPasswordFile =
          if builtins.pathExists ./.wahrwelt-password-hash-enabled then
            "/etc/wahrwelt/hashed-password"
          else
            null;
        secretsDir =
          if builtins.pathExists ./secrets then ./secrets else null;

        extraModules = [ ./configuration.nix ];
        homeExtraModules =
          if builtins.pathExists ./home.nix then [ ./home.nix ] else [ ];
{{ if .Features.SecureBoot }}
        hostInputs = { inherit (inputs) lanzaboote; };
{{ end }}
      };
    };
}
`))

var hostVarsTemplate = template.Must(template.New("host-vars.nix").Funcs(template.FuncMap{
	"nixBool":        nixBool,
	"nixString":      nixString,
	"nixMonitorList": nixMonitorList,
}).Parse(`{
  host = {
    hostname = {{ nixString .Host.Hostname }};
    stateVersion = {{ nixString .Host.StateVersion }};
    configDirectory = "/etc/nixos";
    autoGarbageCollector = true;
    autoOptimiseStore = true;
  };

  user = {
    username = {{ nixString .User.Username }};
    fullName = {{ nixString .User.FullName }};
    homeDirectory = {{ nixString .User.HomeDirectory }};
  };

  locale = {
    timeZone = {{ nixString .Locale.TimeZone }};
    defaultLocale = {{ nixString .Locale.DefaultLocale }};
    extraLocale = {{ nixString .Locale.ExtraLocale }};
    consoleKeyMap = {{ nixString .Locale.ConsoleKeyMap }};
    weatherLocation = {{ nixString .Locale.WeatherLocation }};
  };

  git = {
    username = {{ nixString .Git.Username }};
    email = {{ nixString .Git.Email }};
  };

  packages = {
    preset = {{ nixString .Packages.Preset }};
  };

  noctalia = {
    version = {{ nixString .Noctalia.Version }};
  };

  hardware = {
    gpu = {{ nixString .Hardware.GPU }};
  };

  features = {
    secureBoot = {{ nixBool .Features.SecureBoot }};
    ctfTools = {{ nixBool .Features.CTFTools }};
    omnirouter = {{ nixBool .Features.OmniRouter }};
    portainer = {{ nixBool .Features.Portainer }};
    observability = {{ nixBool .Features.Observability }};
  };

  nix = {
    gcRetention = "14d";
    maxJobs = 1;
    cores = 2;
    swapSizeMiB = 32 * 1024;
    zram = {
      enable = true;
      memoryPercent = 50;
    };
  };

  hypr = {
    keyboardLayouts = {{ nixString .Locale.KeyboardLayouts }};
    keyboardToggle = {{ nixString .Locale.KeyboardToggle }};
    windowOpacity = "0.85";
  };

  display = {
    monitorName = {{ nixString .Display.MonitorName }};
    monitorMode = {{ nixString .Display.MonitorMode }};
    monitorPosition = {{ nixString .Display.MonitorPosition }};
    monitorScale = {{ nixString .Display.MonitorScale }};
    extraMonitors = {{ nixMonitorList .Display.ExtraMonitors }};
  };

  wallpapers = {
    enable = {{ nixBool .Dots.Wallpapers }};
  };
}
`))

func nixBool(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func nixString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, `${`, `''${`)
	return `"` + escaped + `"`
}

func nixMonitorList(monitors []config.Monitor) string {
	if len(monitors) == 0 {
		return "[ ]"
	}
	var b strings.Builder
	b.WriteString("[\n")
	for _, monitor := range monitors {
		b.WriteString("      {\n")
		fmt.Fprintf(&b, "        name = %s;\n", nixString(monitor.Name))
		fmt.Fprintf(&b, "        mode = %s;\n", nixString(monitor.Mode))
		fmt.Fprintf(&b, "        position = %s;\n", nixString(monitor.Position))
		fmt.Fprintf(&b, "        scale = %s;\n", nixString(monitor.Scale))
		b.WriteString("      }\n")
	}
	b.WriteString("    ]")
	return b.String()
}
