#!/usr/bin/env python3
"""Regression tests for the End4 live wallpaper patcher."""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import textwrap
import unittest


sys.dont_write_bytecode = True
PATCHER_PATH = Path(__file__).resolve().parent.parent / "live-wallpapers.py"
SPEC = importlib.util.spec_from_file_location("live_wallpapers", PATCHER_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"unable to load {PATCHER_PATH}")
LIVE_WALLPAPERS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(LIVE_WALLPAPERS)


def switchwall_source(with_flags: bool) -> str:
    flags = '        MPVPAPER_FLAGS="-p -a max"\n' if with_flags else ""
    flag_use = "$MPVPAPER_FLAGS " if with_flags else ""
    return textwrap.dedent(
        f'''\
        CUSTOM_DIR="$XDG_CONFIG_HOME/hypr/custom"
        RESTORE_SCRIPT_DIR="$CUSTOM_DIR/scripts"
        RESTORE_SCRIPT="$RESTORE_SCRIPT_DIR/__restore_video_wallpaper.sh"
        VIDEO_OPTS="no-audio loop hwdec=auto"
        {flags}
        create_restore_script() {{
            local video_path=$1
            cat > "$RESTORE_SCRIPT.tmp" << EOF
        #!/bin/bash
        # Generated by switchwall.sh - Don't modify it by yourself.
        # Time: $(date)

        pkill -f -9 mpvpaper

        for monitor in \\$(hyprctl monitors -j | jq -r '.[] | .name'); do
            mpvpaper {flag_use}-o "$VIDEO_OPTS" "\\$monitor" "$video_path" &
            sleep 0.1
        done
        EOF
            mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
            chmod +x "$RESTORE_SCRIPT"
        }}

        remove_restore() {{
            cat > "$RESTORE_SCRIPT.tmp" << EOF
        #!/bin/bash
        # The content of this script will be generated by switchwall.sh - Don't modify it by yourself.
        EOF
            mv "$RESTORE_SCRIPT.tmp" "$RESTORE_SCRIPT"
        }}

        switch_video() {{
            local video_path="$1"
            local monitor=DP-1
            mpvpaper {flag_use}-o "$VIDEO_OPTS" "$monitor" "$video_path" &
        }}
        '''
    )


class PcSettingsPreviewTest(unittest.TestCase):
    def test_preview_patch_accepts_upstream_indentation_changes(self) -> None:
        patch_preview = getattr(LIVE_WALLPAPERS, "patch_pc_settings_preview", None)
        self.assertIsNotNone(patch_preview, "missing pC settings preview patch helper")

        expression = (
            "source: /\\.(mp4|webm|mkv|avi|mov)$/i.test(Config.options.background.wallpaperPath)\n"
            "    ? Config.options.background.thumbnailPath\n"
            "    : Config.options.background.wallpaperPath"
        )
        replacement = "source: Wallpapers.imageSourceFor(Config.options.background.wallpaperPath)"

        for indentation in (20, 24):
            with self.subTest(indentation=indentation):
                indent = " " * indentation
                source = indent + expression.replace("\n", f"\n{indent}") + "\n"
                expected = indent + replacement + "\n"
                self.assertEqual(patch_preview(source, "QuickConfig fixture"), expected)


class WallpaperServiceDriftTest(unittest.TestCase):
    def test_unreviewed_service_is_rejected_without_replacing_it(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / "services/Wallpapers.qml"
            path.parent.mkdir()
            original = "pragma Singleton\nFolderListModelWithHistory\nproperty string searchQuery\n"
            path.write_text(original)
            with self.assertRaisesRegex(SystemExit, "upstream Wallpapers.qml drifted"):
                LIVE_WALLPAPERS.patch_service(root, "pc")
            self.assertEqual(path.read_text(), original)


class SwitchwallPatchTest(unittest.TestCase):
    def make_restore(self, source: str, video_path: str) -> tuple[list[str], str]:
        patch_switchwall = getattr(LIVE_WALLPAPERS, "patch_switchwall", None)
        self.assertIsNotNone(patch_switchwall, "missing switchwall transformation")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            script = root / "scripts/colors/switchwall.sh"
            script.parent.mkdir(parents=True)
            script.write_text(source)
            patch_switchwall(root)

            config = root / "config"
            restore_dir = config / "hypr/custom/scripts"
            restore_dir.mkdir(parents=True)
            bin_dir = root / "bin"
            bin_dir.mkdir()
            log = root / "mpvpaper.args"
            stubs = {
                "pkill": "#!/bin/sh\nexit 0\n",
                "hyprctl": "#!/bin/sh\nexit 0\n",
                "jq": "#!/bin/sh\nprintf 'DP-1\\n'\n",
                "sleep": "#!/bin/sh\nexit 0\n",
                "mpvpaper": "#!/bin/sh\nprintf '%s\\0' \"$@\" >> \"$MPVPAPER_LOG\"\n",
            }
            for name, contents in stubs.items():
                stub = bin_dir / name
                stub.write_text(contents)
                stub.chmod(0o755)
            env = os.environ.copy()
            env["XDG_CONFIG_HOME"] = str(config)
            env["PATH"] = f"{bin_dir}:{env['PATH']}"
            env["MPVPAPER_LOG"] = str(log)
            generated = subprocess.run(
                [
                    "bash",
                    "-c",
                    'set -e; source "$1"; create_restore_script "$2"',
                    "switchwall-test",
                    str(script),
                    video_path,
                ],
                check=False,
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertEqual(generated.returncode, 0, generated.stderr)
            self.assertEqual(generated.stderr, "")

            restore = restore_dir / "__restore_video_wallpaper.sh"
            self.assertTrue(restore.is_file())
            shebang = restore.read_text().splitlines()[0]
            self.assertTrue(shebang.startswith("#!/"), shebang)
            self.assertTrue(Path(shebang[2:]).is_absolute(), shebang)
            self.assertEqual(Path(shebang[2:]).name, "bash")
            self.assertEqual(
                subprocess.run(["bash", "-n", str(restore)], check=False).returncode,
                0,
            )
            self.assertEqual(generated.stderr, "")

            playback = subprocess.run(
                ["bash", str(restore)],
                check=False,
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertEqual(playback.returncode, 0, playback.stderr)
            self.assertEqual(playback.stderr, "")
            args = log.read_bytes().decode().rstrip("\0").split("\0")
            restore_text = restore.read_text()

            cleared = subprocess.run(
                [
                    "bash",
                    "-c",
                    'set -e; source "$1"; remove_restore',
                    "switchwall-test",
                    str(script),
                ],
                check=False,
                capture_output=True,
                text=True,
                env=env,
            )
            self.assertEqual(cleared.returncode, 0, cleared.stderr)
            clear_shebang = restore.read_text().splitlines()[0]
            self.assertTrue(clear_shebang.startswith("#!/"), clear_shebang)
            self.assertTrue(Path(clear_shebang[2:]).is_absolute(), clear_shebang)
            self.assertEqual(Path(clear_shebang[2:]).name, "bash")
            return args, restore_text

    def test_old_source_quotes_paths_and_keeps_legacy_playback_args(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            marker = Path(directory) / "unexpected"
            video_path = f"wallpaper 'quoted' $(touch {marker}).mp4"
            args, restore_text = self.make_restore(switchwall_source(False), video_path)

            self.assertEqual(
                args,
                ["-o", "no-audio loop hwdec=auto", "DP-1", video_path],
            )
            self.assertFalse(marker.exists())
            self.assertTrue(restore_text.splitlines()[0].startswith("#!/"))

    def test_new_source_preserves_mpvpaper_flags_in_generated_playback(self) -> None:
        video_path = "/home/user/Wallpapers/slow dance.mp4"
        args, _ = self.make_restore(switchwall_source(True), video_path)

        self.assertEqual(
            args,
            ["-p", "-a", "max", "-o", "no-audio loop hwdec=auto", "DP-1", video_path],
        )

    def test_new_source_accepts_spacing_changes(self) -> None:
        source = switchwall_source(True).replace(
            "mpvpaper $MPVPAPER_FLAGS -o",
            "mpvpaper  $MPVPAPER_FLAGS   -o",
        )
        args, _ = self.make_restore(source, "/home/user/Wallpapers/slow dance.mp4")

        self.assertEqual(args[:5], ["-p", "-a", "max", "-o", "no-audio loop hwdec=auto"])

    def test_dynamic_or_inconsistent_mpvpaper_flags_are_rejected(self) -> None:
        source = switchwall_source(True)
        invalid_sources = (
            source.replace('MPVPAPER_FLAGS="-p -a max"', 'MPVPAPER_FLAGS="$(unsafe)"'),
            source.replace("mpvpaper $MPVPAPER_FLAGS -o", "mpvpaper -o", 1),
            source + '\nMPVPAPER_FLAGS="-p -a max"\n',
            source.replace("create_restore_script()", "create_restore_file()"),
            source + "\nmpvpaper $MPVPAPER_FLAGS -o \\\"$VIDEO_OPTS\\\" \\\"$monitor\\\" \\\"$video_path\\\" &\n",
        )
        for invalid in invalid_sources:
            with self.subTest(source=invalid[:80]):
                with tempfile.TemporaryDirectory() as directory:
                    root = Path(directory)
                    script = root / "scripts/colors/switchwall.sh"
                    script.parent.mkdir(parents=True)
                    script.write_text(invalid)

                    with self.assertRaisesRegex(SystemExit, "switchwall"):
                        LIVE_WALLPAPERS.patch_switchwall(root)

                    self.assertEqual(script.read_text(), invalid)


if __name__ == "__main__":
    unittest.main()
