package tui

import (
	"fmt"

	"github.com/TakuyaYagam1/wahrwelt/Linux/installer/internal/config"
)

func sectionPreview(m sectionModel) []string {
	s := m.state
	switch selectedSection(m) {
	case "General":
		return previewGeneral(s)
	case "User":
		return previewUser(s)
	case "Region":
		return previewRegion(s)
	case "Display":
		return previewDisplay(s)
	case "Packages":
		return previewPackages(s)
	case "Services":
		return previewServices(s)
	case "Dots":
		return previewDots(s)
	case "Passwords":
		return previewPasswords(m)
	case "Cleanup":
		return previewCleanup()
	case "Doctor":
		return previewDoctor()
	case "Apply":
		return previewApply()
	case "Quit":
		return previewQuit()
	default:
		return previewDefault(s)
	}
}

func previewGeneral(s config.State) []string {
	return previewSettings(
		previewSetting("Hostname", "Flake target and networking host name.", s.Host.Hostname),
		previewSetting("Wahrwelt channel", "Branch followed by the installed /etc/nixos wrapper.", sourceChannelLabel(s.Source.Channel)),
		previewSetting("Noctalia version", "Selects the current v5 shell integration or the preserved legacy v4 config seed.", noctaliaVersionLabel(s.Noctalia.Version)),
		previewSetting("State version", "NixOS compatibility baseline for this machine.", s.Host.StateVersion),
	)
}

func previewUser(s config.State) []string {
	return previewSettings(
		previewSetting("Username", "Linux account name used by users/user.nix and Home Manager.", s.User.Username),
		previewSetting("Full name", "Display name stored in the generated user module.", s.User.FullName),
		previewSetting("Home directory", "User home used by Home Manager and dots install paths.", s.User.HomeDirectory),
		previewSetting("Git identity", "Git user.name and user.email written by Home Manager.", fmt.Sprintf("%s <%s>", s.Git.Username, s.Git.Email)),
	)
}

func previewRegion(s config.State) []string {
	return previewSettings(
		previewSetting("Timezone", "Nix time.timeZone value.", s.Locale.TimeZone),
		previewSetting("Default locale", "Primary glibc locale generated by NixOS.", s.Locale.DefaultLocale),
		previewSetting("Extra locale", "Additional generated locale for regional tools/input.", s.Locale.ExtraLocale),
		previewSetting("Console keymap", "TTY keyboard map only. Hypr graphical layouts use XKB.", s.Locale.ConsoleKeyMap),
		previewSetting("Hypr/XKB layouts", "Graphical keyboard layouts from xkeyboard-config.", s.Locale.KeyboardLayouts),
		previewSetting("Keyboard toggle", "Hyprland kb_options value for layout switching.", s.Locale.KeyboardToggle),
		previewSetting("Weather location", "City name used by shell/weather widgets.", s.Locale.WeatherLocation),
	)
}

func previewDisplay(s config.State) []string {
	settings := make([][]string, 0, 4+len(s.Display.ExtraMonitors))
	settings = append(settings,
		previewSetting("GPU", "Selects driver/session defaults for the system config.", s.Hardware.GPU),
		previewSetting("Monitor (primary)", "Generates: monitor = <line>; `preferred` collapses to ,preferred,auto,scale.", s.Display.MonitorLine()),
	)
	for i, monitor := range s.Display.ExtraMonitors {
		settings = append(settings, previewSetting(
			fmt.Sprintf("Monitor (extra #%d)", i+1),
			"Additional output rendered after the primary monitor in monitors.conf.",
			monitor.MonitorLine(),
		))
	}
	return previewSettings(settings...)
}

func previewPackages(s config.State) []string {
	return previewSettings(
		previewSetting("Package preset", "Developer keeps a lean workstation; Personal adds heavy apps, alternatives and private defaults.", s.Packages.Preset),
		previewSetting("CTF tools", "Adds heavy reverse/pwn/web/forensics tooling.", formatBool(s.Features.CTFTools)),
		previewSetting("Secure Boot", "Lanzaboote should stay disabled unless the machine is prepared.", formatBool(s.Features.SecureBoot)),
	)
}

func previewServices(s config.State) []string {
	return previewSettings(
		previewSetting("OmniRouter", "Builds/enables the local OmniRouter package and module.", formatBool(s.Features.OmniRouter)),
		previewSetting("Portainer", "Enables a localhost container UI connected to the selected per-user engine.", formatBool(s.Features.Portainer)),
		previewSetting("Observability", "Enables the localhost Grafana/Prometheus/Loki stack.", formatBool(s.Features.Observability)),
	)
}

func previewDots(s config.State) []string {
	return previewSettings(
		previewSetting("Noctalia version", "Controls which Noctalia Home Manager integration and seed assets are used.", noctaliaVersionLabel(s.Noctalia.Version)),
		previewSetting("Hypr dots", "Mirrors Linux/dots/hypr into ~/.config/hypr and reloads Hypr if running.", formatBool(s.Dots.Hypr)),
		previewSetting("Wallpapers", "Copies repo wallpapers into ~/Pictures/Wallpapers.", formatBool(s.Dots.Wallpapers)),
		previewSetting("Zen Catppuccin chrome", "Installs the Zen Browser Catppuccin chrome theme.", formatBool(s.Dots.ZenTheme)),
		previewSetting("Sine profile files", "Best-effort Zen Sine files install from pinned URLs.", formatBool(s.Dots.Sine)),
		previewSetting("Neovim config", "Backs up/syncs the repo Neovim config.", formatBool(s.Dots.Neovim)),
		previewSetting("v2rayN sing-box", "Copies sing-box support into v2rayN when detected.", formatBool(s.Dots.V2rayN)),
	)
}

func previewPasswords(m sectionModel) []string {
	return previewSettings(
		previewSettingWithLabel("Linux user password", "Enter a new value only when changing it. If already present on disk, Apply preserves it when left blank.", "status", secretStatus(m.secrets.UserPassword, m.existingSecrets.UserPassword, "not entered")),
		previewSettingWithLabel("State safety", "Plain passwords are kept only in memory for this installer run. They are never written to draft.json.", "status", "session-only"),
	)
}

func previewCleanup() []string {
	return previewSettings(
		previewSettingWithLabel("Managed cleanup", "Removes Wahrwelt-managed stale files and caches.", "action", "explicit"),
		previewSettingWithLabel("Backups", "Unmanaged configs are backed up before removal candidates are touched.", "status", "enabled"),
	)
}

func previewDoctor() []string {
	return previewSettings(
		previewSettingWithLabel("System checks", "Checks /etc/nixos mirror, hardware config and flake target.", "mode", "read-only"),
		previewSettingWithLabel("Hypr checks", "Checks runtime shell state, entrypoints, scripts and wallpaper state consistency.", "mode", "read-only"),
		previewSettingWithLabel("Recovery hints", "Shows backup paths and commands when something looks wrong.", "mode", "read-only"),
	)
}

func previewApply() []string {
	return previewSettings(
		previewSettingWithLabel("Stage config", "Builds a temporary flake containing host hardware, local overrides, flake.lock and generated variables.", "order", "1"),
		previewSettingWithLabel("Dry-build", "Runs nixos-rebuild dry-build against the staging flake before touching /etc/nixos.", "order", "2"),
		previewSettingWithLabel("Mirror /etc/nixos", "After dry-build success, backs up /etc/nixos and syncs the staging mirror.", "order", "3"),
		previewSettingWithLabel("Apply dots", "Applies selected user dots in the same session and reloads Hypr when available.", "order", "4"),
		previewSettingWithLabel("Switch", "TUI always asks before nixos-rebuild switch.", "order", "5"),
	)
}

func previewQuit() []string {
	return previewSettings(
		previewSettingWithLabel("Quit installer", "Exit without applying changes.", "action", "no-op"),
	)
}

func previewDefault(s config.State) []string {
	return previewSettings(
		previewSetting("Host", "Current NixOS host name.", s.Host.Hostname),
		previewSetting("User", "Current account name.", s.User.Username),
		previewSetting("Packages", "Current package preset.", s.Packages.Preset),
		previewSetting("GPU", "Current GPU profile.", s.Hardware.GPU),
	)
}

func previewSettings(settings ...[]string) []string {
	var lines []string
	for _, setting := range settings {
		lines = append(lines, setting...)
		lines = append(lines, "")
	}
	if len(lines) > 0 {
		lines = lines[:len(lines)-1]
	}
	return lines
}

func previewSetting(name, description, value string) []string {
	return previewSettingWithLabel(name, description, "current", value)
}

func previewSettingWithLabel(name, description, label, value string) []string {
	return []string{
		previewHeadingPrefix + name,
		description,
		previewValuePrefix(label) + value,
	}
}

func formatBool(value bool) string {
	if value {
		return "enabled"
	}
	return "disabled"
}
